name: boostsecurity.io
run-name: ${{fromJSON(github.event.inputs.scan_params).run_name}}
permissions: {}
on:
  workflow_dispatch:
    inputs:
      job_name:
        description: Name of the job to run
        required: false
      scan_params:
        description: The scan parameters
        required: true

jobs:
  boost-scanner:
    name: ${{fromJSON(github.event.inputs.scan_params).trigger_id}}
    runs-on: ubuntu-latest
    steps:
      - name: ${{fromJSON(github.event.inputs.scan_params).trigger_id}}
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{secrets.BOOST_API_TOKEN}}
          trigger_id: ${{fromJSON(github.event.inputs.scan_params).trigger_id}}